### ISSUE TITLE
Unnecessary use of regulated finance words

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#30]
The product smart contract and documentation make unnecessary use of words that are specifically related to finance. These include "currency," "DeFi," and "AUM" (assets under management). My understanding is that Treasure and the Harvesters feature are a game, not a bank; and the participants are players, not employees or investors. Use of words that specifically relate to regulated financial activities may increase the risk that regulators in some jurisdiction will be confused as to the nature of this product.

**Recommendations:**

1. Replace "currency" -> "in-game currency" everywhere. Make no mention of using MAGIC outside the game nor of marketplaces that may or may not be available outside the game.
2. Remove any mention of "DeFi" everywhere.
3. Replace "AUM" -> "depositAmount" or "totalDeposits" everywhere.
4. Carefully review if "vesting" or "principal" require similar treatment.

**Comment by ghoul-sol** [comment]
Other tickets were prioritized instead.
