### ISSUE TITLE
Unnecessary use of gendered word for primary controller

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#32]
Implementation uses `Middleman` to describe the primary controller which has access to and grants all rewards.

The word "middleman" is unnecessarily gender-favoring. Smart contracts are published forever, so it is important to be particularly sensitive to inclusivity issues.

**Recommendation:** substitute this word for "reward controller" or "middle person" or similar

**Comment by ghoul-sol** [comment]
Other tickets were prioritized instead.
