### ISSUE TITLE
HarvestFactory grants all permissions to a single account

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#42]
In `HarvesterFactory`, three separate administrative roles are granted to the same account:

```solidity
_grantRole(HF_ADMIN, _admin);
_grantRole(HF_DEPLOYER, _admin);
_grantRole(HF_BEACON_ADMIN, _admin);
```

Granted multiple roles to the same account creates a security risk of privilege escalation when using the features of the lesser role and violates the principle of least privilege.

**Recommendation**: grant only the `HF_ADMIN` role here

**Comment by ghoul-sol** [comment]
All roles are granted to the same wallet so that wallet can configure the system properly and renounce it afterward.
