### ISSUE TITLE
Inconsistent use of option `override` keyword for implementation of interface

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#43]
Since Solidity 0.8.8, it is optional to use the `override` keyword when implementing an interface function. The implementation here both uses (e.g. `ExtractorStakingRules.getUserBoost`) and does not use (e.g. `ExtractorStakingRules.getHarvesterBoost`) this feature.

Inconsistent conventions while coding reduces readability and increases the risk of error.

**Recommendation**: select one or the other, document the choice in README.md under heading Code Style and use that consistently.

**Comment by ghoul-sol** [comment]
Other tickets were prioritized instead.
