### ISSUE TITLE
Conflicting requirements on MAGIC staking utilization multiplier

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#44]
The documentation states (2.3) that Harvester emissions "gradually increase" and "steadily increase" based on the MAGIC staked. Later in that section a step function is introduced for this same variable. A step function is not gradual or steady.

Conflicting specifications guarantees that the implementation will be incongruent with at least one of them.

**Recommendations:**

1. Document for a gradual function or a step function.
2. If using the step function, clearly specify whether each limit is part of the lower or higher step (e.g. is 3.6M MAGIC rated at 70% or 80% emissions). Likewise for the corruption documentation.
3. Update mentions of default 10m MAGIC in documentation and implementation at `totalDepositCap`.

**Comment by ghoul-sol** [comment]
Other tickets were prioritized instead.
