### ISSUE TITLE
Corruption modifier specification is not specific enough

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#45]
The documentation (2.3.5) puts forth a corruption-to-debuff table. But the table includes each intermediary bound (e.g. 400,000) in two different rows.

This may result in `MiddleMan.getCorruptionNegativeBoost` having an off-by-one error compared to what is expected.

**Recommendations:**

1. Clarify the documentation
2. Update implementation to match the documentation

**Comment by ghoul-sol** [comment]
It’s a good point but not a critical issue as this feature is manually operated. It’s good to be aware where the next step begins though. For example, 100,000.00 corruption token balance does not create a negative boost. 100,000.01 is required to do so. Please review @peitalin

**Comment by peitalin** [comment]
Great thanks, we will clarify in the documentation and clarify cutoff points
