### ISSUE TITLE
Legion boost average rank is vulnerable to griefing attack

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#46]
In the documentation, and the implementation in `LegionStakingRules`, any player is able to stake legions to any harvester.

Because of the *legion rank boost*, this means that an griefing attack / sabotage strategy exists where players will stake a legion with low rank to reduce the boost of a harvester (`totalRank`).

I understand that other game design choices have been made to make the primary win be positive competition rather than negative sabotage. Also, depending on the availability of legions, game parameters in use, and game market conditions, the sabotage strategy may be more effective than other strategies, which may violate the goal (section 1) of having harvesters function as NFT sinks.

**Recommendation**: review if this design is intentional and if not, change accordingly

**Comment by ghoul-sol** [comment]
> The marginal contribution of a griefer is small (to the average legion rank), and the griefer will lose out on farming Treasures in the meantime so it’s a -EV decision to grieve.
