### ISSUE TITLE
Major administrative functions with dire consequences are not listed as "emergency" functions

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#48]
In `AtlasMine`, the `setTreasure` function can lead to very ugly situations—existing staked deposits will be unrecoverable, and deposits on the new `treasure` are indistinguishable from deposits on the old `treasure` so people may receiving the wrong token (somebody else's) back. It also messes up `treasureStakedAmount` because people may get locked and cannot unstake.

In `AtlasMine` and possible `MasterOfCoinV1`, the `setMagicToken` has similar issues.

Another function elsewhere `toggleUnlockAll` is described as an "emergency" function.

**Recommendation**: updated documentation to describe `setTreasure` and `setMagicToken` as "emergency" functions and explain the known issues; or remove those functions altogether; or update implementations to handle multiple tokens to cleanly exit old tokens

**Comment by ghoul-sol** [comment]
“Emergency” comment could be added but it was not the intention of the design. Contracts are designed to provide maximum flexibility for updates. Users must trust the governance process of Treasure.
