### ISSUE TITLE
Design does not differentiate between fixed and configurable parameters

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#49]
Some of the formulas and constants such as the range of allowed harvester modifiers from legions are run-time configurable.

The documentation does not differentiate from options that are fixed in the implementation versus items that can be changed after deployment.

This may result in the implementation not meeting the expectation of designers and may result in unexpected or erroneous functionality if administrators configure to parameters after deployment which the developers and this reviewer are not expecting.

For example, because the `maxStakeableTotal` configurable option is multiplied by 10^18 *and then squared*, its range of allowable values is much smaller than 2^256. ERC-1155 allow large numbers of tokens up to 2^256.

**Recommendations**

1. Note in the documentation any specifications which are subject to change in operations (everything else is understood to be an invariant specification).
2. Note in function-level documentation (and possibly check in code) any required input range.

**Comment by ghoul-sol** [comment]
Contracts are designed to provide maximum flexibility for updates. Users must trust the governance process of Treasure.

However, there are plans to improve documentation in the future to further clarify parameters' values. I'll close this one as we have other issues open for documentation.
