### ISSUE TITLE
Legions boost is missing boost factor

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#50]
The documentation includes (2.3.2) a formula for calculating legions boost.

This formula does not include the legions boost factor. It appears that this factor is desired.

**Recommendation**: add LegionsBoostFactor to the formula.

**Comment by ghoul-sol** [comment]
> Code is correct and adds `boostFactor` which is configurable. It was simply missing in the whitepaper formula

Documentation fixed.
