### ISSUE TITLE
Design does not specify what happens to disabled harvesters' emissions share

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#51]
Harvesters can be created but not deleted, only disabled.

Documentation does not specify whether a disabled harvester will participate in allocation of Bridgeworld emissions (i.e. dilute rewards from other harvesters), nor whether emissions shall accrue to players during the time it is disabled.

These are important considerations and affect the envisioned war contract (documentation 3.3).

**Recommendation**: decide on these points and update the documentation and implementation to match these decisions

**Comment by ghoul-sol** [comment]
Fixed by #80

**Comment by fulldecent** [comment]
@ghoul-sol FYI, added follow-on issue here ^
