### ISSUE TITLE
💣 Legion ranks matrix incorrect

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#52]
The documentation specifies to "change legion ranks matrix" to new values.

But the implementation does not appear to use those new values.

For example, auxiliary rare is specified at 1.2 boost. But `LegionStakingRules`'s constructor sets this to 0.25.

**Recommendation**: decide on intended values and update the documentation and implementation to match

**Comment by ghoul-sol** [comment]
Fixed, pending review from @peitalin
