### ISSUE TITLE
💣 Treasure boosts incorrect

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#54]
The documentation provides values of boosts for staking treasures.

But the implementation does not use all those specified values.

For example, honeycomb is specified to have a boost of 15.78% but the implementation uses a boost of 15.8%. It appears that values were rounded.

**Recommendation**: decide on intended values and update the documentation and implementation to match

**Comment by ghoul-sol** [comment]
@peitalin 
> Treasure boosts were rounded in Atlas Mine, so will keep it consistent in Harvesters. I will update the documentation to reflect this. Consider fixed.
