### ISSUE TITLE
💣 Player stakes cannot be removed if harvester disabled

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#55]
The documentation states (3.3) that a "disabled" harvester will allow players to exit. 

It appears that "exit" means players are able to perform `withdrawPosition` regardless of locking commitments.

However the implementation does not implement this logic, instead unrestrained exiting is allowed only under the emergency `unlockAll` condition, not the disabled condition.

**Recommendation**: decide on desired behavior and update the documentation and implementation to match

**Comment by ghoul-sol** [comment]
@peitalin 
> Users will not be unlocked if the harvester is disabled. We will limit lockups to 2 weeks options so they will wait that period out. Harvesters as disabled if they lose a battle, we don’t want to allow guilds to deliberately lose to unlock their deposits.
Consider this already fixed.
