### ISSUE TITLE
💣 Extractor boosts are not effective for their full lifetime

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#56]
The documentation states (2.3.3) that an extractor boost shall be effective for three hours.

In plain language, this means the integral of the harvester emissions over that time period should all be increased by the effective amount. i.e. "three hours' worth".

However in the implementation, the actual accrued amount will always be less than the specified amount. This is because the boost will only be applied when harvesting and if harvesting is done after the boost expires then any boosting active in that time period will be forfeited.

Even if harvesting is done every second, some amount will be forfeited because emissions are harvested "at the end" of each second and the boost only applies up the lifetime.

**Recommendation**: keep existing implementation and update documentation to state "up to three hours", this will create an incentive to spam harvesting around the time any extractor will expire, which may or may not be significant to gameplay

**Comment by ghoul-sol** [comment]
@peitalin 
> I have updated the Extractor documentation to reflect the need to harvest as close to expiry as possible to maximize rewards. Consider fixed.
