### ISSUE TITLE
💣 The liquidity pool can leak liquidity leading to a run on the bank

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#60]
The amount of users boosts granted when staking a legion is not necessarily the same amount removed when unstaking. This is because `getNftBoost` is not a pure function and it depends on `getLegionBoost` which can be effectively changed using `setLegionBoostMatrix` for example in `AtlasMine`.

This will result in LP not equalling the sum of its parts when `setLegionBoostMatrix` is called. This could result in a "run on the bank" if `setLegionBoostMatrix` values are ever increased. This run might not be seen until `toggleUnlockAll` is attempted, compounding any emergency at that time.

**Recommendation**: save the boost amount into storage at the time of staking and use that same amount when unstaking.

**Comment by ghoul-sol** [comment]
The team discussed this in length and concluded that critical metadata that can influence AtlasMine calculations will never be changed. That said, no changes will be made to AtlasMine implementation.
