### ISSUE TITLE
💣 1/1 legions can get stuck after setInitialMetadataForLegion

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#61]
The deployed https://arbiscan.io/address/0x99193EE9229b833d2aA4DbBdA697C6600b944286#readProxyContract `LegionMetadataStore` allows admin to change the metadata for any legion at any time using the function named `setInitialMetadataForLegion`. This breaks an assumption in `AtlasMine`'s `stakeLegion`/`unstakeLegion` which assume that the one-of-oneness of legions is unchangeable. (i.e. that function is incorrectly named, it allows to set at *any* time, not just initially.)

**Recommendations:**

1. Document this risk.
2. Set operational controls around using `setInitialMetadataForLegion` if this is not intended behavior.
3. If warranted, store the one-of-oneness of a legion when staking and read that stored value when unstaking.

**Comment by ghoul-sol** [comment]
The team discussed this in length and concluded that critical metadata that can influance AtlasMine calculations will never be changed. That said, no changes will be made to AtlasMine implementation.
