### ISSUE TITLE
💣 Any NFT can get stuck after _setNftConfig

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#62]
In `NftHandler`, if a customer stakes an NFT and then the admin will use `_setNftConfig` to disable the NFT then the customer can no longer unstake it.

**Recommendation**: 

1. Track the interface detection at time of staking to allow later unstaking even if it is disabled; and/or
2. Separate out the admin feature to disable/modify an NF config (dangerous) from the the feature to add a new NFT config (safe).

**Comment by ghoul-sol** [comment]
Fixed by #84
