### ISSUE TITLE
Divide-by-zero if admin performs multiple operations at once

### ISSUE THREAD

**Issue by fulldecent** [ghoul-sol/treasure-staking#64]
Multiple operations are performed at once, relating to updating `lastRewardTimestamp` and then updating a pool, then a divide-by-zero will occur and the operation will fail.

* `MasterOfCoin._fundStream` (and V1)
* `MasterOfCoin.updateStreamTime`
* `MasterOfCoinV1.addStream`

This is implemented in `Middleman` with the `runIfNeeded ` modifier.

**Recommendation**: consider if this all divide by errors are undesirable and create a separate error message for this if desired

**Comment by ghoul-sol** [comment]
Other tickets were prioritized instead.
